# Edit Distance

## Recursive Brute Force Solution

In [2]:
def edit_distance(s: str, t: str) -> int:
    
    def distance(i: int, j: int) -> int:
        if i == 0: return j   # s is empty, j insertions
        if j == 0: return i   # t is empty, i deletions
        
        # case 1 - change
        if s[i-1] == t[j-1]:
            changes = distance(i-1, j-1)
        else:
            changes = 1 + distance(i-1, j-1)
            
        # case 2 - deletions
        deletions = 1 + distance(i-1, j) 
        
        # case 3 - insertions
        insertions = 1 + distance(i, j-1)
        
        return min(changes, insertions, deletions)
    
    return distance(len(s), len(t))
        

In [3]:
s = "snowy"
t = "sunny"
print(edit_distance(s,t))

3


In [4]:
s = 'polynomial'
t = 'exponential'
print(edit_distance(s,t))

6


## Edit Distance - Dynamic Programming

In [1]:
import numpy as np
def edit_distance(s: str, t: str) -> int:
    dist = np.zeros((len(s) + 1, len(t) + 1)) # (m+1)(n+1) O(mn)
    # let m be len(s), n be len(t)
    # initialize the first row
    for j in range(len(t) + 1): dist[0][j] = j # O(n)
        
    # initialize the first column
    for i in range(len(s) + 1): dist[i][0] = i # O(m)
    
    # O(mn)
    for i in range(1, len(s)+1): # m
        for j in range(1, len(t)+1): # n
            dist[i][j] = min(
                1 + dist[i-1][j], # deletion
                1 + dist[i][j-1], # insertion
                dist[i-1][j-1] + (0 if s[i-1] == t[j-1] else 1) # change
            )
    return dist 
    

In [6]:
edit_distance("horse", "ror")

[[0. 1. 2. 3.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [3. 0. 0. 0.]
 [4. 0. 0. 0.]
 [5. 0. 0. 0.]]


In [2]:
print(edit_distance("repeal", "treat"))

[[0. 1. 2. 3. 4. 5.]
 [1. 1. 1. 2. 3. 4.]
 [2. 2. 2. 1. 2. 3.]
 [3. 3. 3. 2. 2. 3.]
 [4. 4. 4. 3. 3. 3.]
 [5. 5. 5. 4. 3. 4.]
 [6. 6. 6. 5. 4. 4.]]
